export const TOPIC_REPOSITORY = Symbol("TOPIC_REPOSITORY");
export const USER_REPOSITORY = Symbol("USER_REPOSITORY");
export const TOPIC_GENERATION_LOCK_REPOSITORY = Symbol(
  "TOPIC_GENERATION_LOCK_REPOSITORY"
);
